name: Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'

jobs:
  swift-test:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macOS-latest, macOS-11]
        swift-version: ["5.3.3", "5.4.2"]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Build
        run: swift build
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
      - name: Run tests
        run: swift test
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
  xcode-test:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macOS-11]
        xcode-version: ["12.5.1"]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: sinoru/actions-setup-xcode@v2
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: bot@sinoru.io
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies
      - name: Build with Analyze
        run: |
          xcodebuild -scheme swift-zip \
            -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" \
            -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation),OS=latest" \
            -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=latest" \
            analyze
      - name: Test
        run: |
          xcodebuild -scheme swift-zip \
            -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" \
            -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation),OS=latest" \
            -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=latest" \
            -retry-tests-on-failure \
            test-without-building
